const pptxgen = require('pptxgenjs');

const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE';
pptx.author = 'AutoSDLC Team';
pptx.subject = 'AutoSDLC Story Generator technical presentation';
pptx.title = 'AutoSDLC Story Generator';
pptx.company = 'AutoSDLC';
pptx.lang = 'en-IN';
pptx.theme = {
  headFontFace: 'Aptos Display', bodyFontFace: 'Aptos', lang: 'en-US'
};
pptx.defineLayout({ name: 'CUSTOM_WIDE', width: 13.333, height: 7.5 });
pptx.layout = 'CUSTOM_WIDE';
pptx.defineSlideMaster({
  title: 'MASTER',
  background: { color: 'F7F9FC' },
  objects: [
    { rect: { x: 0, y: 0, w: 13.333, h: 0.13, fill: { color: '4F46E5' }, line: { color: '4F46E5' } } },
    { text: { text: 'AutoSDLC Story Generator', options: { x: 0.45, y: 7.12, w: 5, h: 0.18, fontFace: 'Aptos', fontSize: 8, color: '64748B', margin: 0 } } },
    { text: { text: 'Technical walkthrough', options: { x: 10.65, y: 7.12, w: 2.2, h: 0.18, fontFace: 'Aptos', fontSize: 8, color: '64748B', align: 'right', margin: 0 } } },
  ],
  slideNumber: { x: 12.9, y: 7.1, color: '64748B', fontFace: 'Aptos', fontSize: 8 }
});

const C = { navy:'102A43', ink:'172B4D', indigo:'4F46E5', blue:'2563EB', teal:'0F766E', green:'16A34A', amber:'D97706', red:'DC2626', muted:'64748B', pale:'EEF2FF', bg:'F7F9FC', white:'FFFFFF', line:'D9E2EC' };
const SH = pptx.ShapeType;
function slide(title, subtitle='') { const s=pptx.addSlide('MASTER'); s.addText(title,{x:.55,y:.42,w:12,h:.42,fontSize:25,bold:true,color:C.navy,margin:0}); if(subtitle)s.addText(subtitle,{x:.57,y:.92,w:12,h:.26,fontSize:10.5,color:C.muted,margin:0}); return s; }
function text(s,t,x,y,w,h,opts={}) { s.addText(t,{x,y,w,h,fontSize:opts.fontSize||14,color:opts.color||C.ink,bold:opts.bold||false,breakLine: false,fit:'shrink',margin:opts.margin===undefined?.08:opts.margin,bullet:opts.bullet,paraSpaceAfterPt:opts.paraSpaceAfterPt||0,breakLine:opts.breakLine,align:opts.align||'left',valign:opts.valign||'mid'}); }
function box(s,x,y,w,h,title,body,accent=C.indigo) { s.addShape(SH.roundRect,{x,y,w,h,rectRadius:.08,fill:{color:C.white},line:{color:C.line,width:1}}); s.addShape(SH.rect,{x,y,w:.075,h,fill:{color:accent},line:{color:accent}}); text(s,title,x+.22,y+.15,w-.35,.25,{fontSize:13,bold:true,color:C.navy}); text(s,body,x+.22,y+.52,w-.36,h-.62,{fontSize:10.5,color:C.muted,valign:'top'}); }
function pill(s,t,x,y,w,color=C.pale,ink=C.indigo){s.addShape(SH.roundRect,{x,y,w,h:.32,rectRadius:.12,fill:{color},line:{color}});text(s,t,x,y+.035,w,.18,{fontSize:8.5,bold:true,color:ink,align:'center',margin:0});}
function arrow(s,x1,y1,x2,y2,color=C.indigo){s.addShape(SH.line,{x:x1,y:y1,w:x2-x1,h:y2-y1,line:{color,width:2,beginArrowType:'none',endArrowType:'triangle'}})}

// 1
{const s=pptx.addSlide();s.background={color:C.navy};s.addShape(SH.rect,{x:0,y:0,w:13.333,h:.14,fill:{color:'818CF8'},line:{color:'818CF8'}});s.addText('AutoSDLC\nStory Generator',{x:.7,y:1.12,w:7.6,h:1.4,fontSize:37,bold:true,color:C.white,breakLine:false,margin:0});s.addText('An AI-powered system that turns project briefs into execution-ready epics, stories, tasks, and manual test cases.',{x:.73,y:2.8,w:6.9,h:.65,fontSize:17,color:'CBD5E1',breakLine:false,margin:0});pill(s,'React + FastAPI + LiteLLM',.73,4.12,2.45,'312E81','E0E7FF');pill(s,'Structured AI pipeline',3.33,4.12,2.25,'312E81','E0E7FF');pill(s,'Redmine-ready output',5.72,4.12,2.05,'312E81','E0E7FF');s.addShape(SH.roundRect,{x:9.05,y:1.05,w:3.35,h:4.7,rectRadius:.16,fill:{color:'1E3A5F'},line:{color:'64748B',width:1}});['Project brief','AI decomposition','Validated backlog','Redmine / Excel'].forEach((t,i)=>{const y=1.47+i*1.02;s.addShape(SH.roundRect,{x:9.46,y,w:2.53,h:.53,rectRadius:.1,fill:{color:i===1?'4F46E5':'274C77'},line:{color:i===1?'818CF8':'274C77'}});text(s,t,9.46,y+.12,2.53,.2,{fontSize:11,bold:true,color:C.white,align:'center',margin:0});if(i<3)arrow(s,10.72,y+.57,10.72,y+.9,'A5B4FC')});s.addText('Technical presentation',{x:.73,y:6.56,w:3,h:.25,fontSize:10,color:'94A3B8',margin:0});}

// 2
{const s=slide('What problem does it solve?','From ambiguous requirements to a reviewable, traceable delivery plan.');box(s,.65,1.45,3.82,3.65,'The usual bottleneck','• Briefs vary wildly in detail\n• Teams manually decompose scope\n• Acceptance criteria are inconsistent\n• Handoffs into issue trackers are slow',C.red);box(s,4.76,1.45,3.82,3.65,'What this application does','• Ingests a brief or uploaded document\n• Produces backlog hierarchy\n• Flags uncertainty and gaps\n• Lets teams review, edit, export, or push',C.indigo);box(s,8.87,1.45,3.82,3.65,'Business value','• Faster planning and estimation\n• Better story consistency\n• QA coverage starts earlier\n• Repeatable delivery workflow',C.green);s.addShape(SH.roundRect,{x:1.65,y:5.62,w:10.05,h:.56,rectRadius:.08,fill:{color:'E0E7FF'},line:{color:'C7D2FE'}});text(s,'The goal is not “AI writes tickets”; it is a controlled backlog-generation workflow with visible quality signals.',1.9,5.78,9.55,.2,{fontSize:13,bold:true,color:'3730A3',align:'center',margin:0});}

// 3
{const s=slide('End-to-end product workflow','A brief becomes a structured delivery artifact through a staged workflow.');const items=[['1','Input','Paste a project idea or upload Markdown / Word'],['2','Pre-flight','Validate brief quality and ask focused clarifications'],['3','Generate','Create epics → stories → tasks → QA cases'],['4','Review','Score quality, surface gaps, edit hierarchy'],['5','Deliver','Persist locally, export Excel, or push to Redmine']];items.forEach((a,i)=>{const x=.55+i*2.53;s.addShape(SH.roundRect,{x,y:1.8,w:2.12,h:2.65,rectRadius:.1,fill:{color:C.white},line:{color:C.line}});s.addShape(SH.ellipse,{x:x+.77,y:1.49,w:.55,h:.55,fill:{color:C.indigo},line:{color:C.indigo}});text(s,a[0],x+.77,1.64,.55,.18,{fontSize:12,bold:true,color:C.white,align:'center',margin:0});text(s,a[1],x+.2,2.2,1.72,.25,{fontSize:14,bold:true,color:C.navy,align:'center',margin:0});text(s,a[2],x+.2,2.72,1.72,1.08,{fontSize:10.5,color:C.muted,align:'center',valign:'top'});if(i<4)arrow(s,x+2.14,3.12,x+2.47,3.12,C.indigo)});text(s,'Live progress is streamed to the frontend through Server-Sent Events (SSE), so users see generated hierarchy items as they arrive.',.85,5.32,11.6,.35,{fontSize:14,color:C.teal,align:'center'});}

// 4
{const s=slide('Technical architecture','A decoupled frontend/backend design with a provider abstraction layer.');box(s,.55,1.45,2.25,3.9,'Frontend','React + TypeScript\nVite development server\nModular components\nLive SSE progress\nVite API proxy',C.blue);box(s,3.05,1.45,2.25,3.9,'API layer','FastAPI + Uvicorn\nREST endpoints\nPydantic schemas\nUpload handling\nError responses',C.indigo);box(s,5.55,1.45,2.25,3.9,'AI orchestration','Phase pipeline\nPrompt templates\nLiteLLM client\nRetries + fallback\nQuota tracking',C.teal);box(s,8.05,1.45,2.25,3.9,'Data & services','SQLite persistence\nExcel export\nDocument extraction\nMetrics & validation\nRedmine client',C.amber);box(s,10.55,1.45,2.25,3.9,'Integrations','Groq\nCerebras\nGemini\nRedmine REST API\nOptional Docker stack',C.green);[2.8,5.3,7.8,10.3].forEach(x=>arrow(s,x,3.4,x+.24,3.4,C.indigo));s.addShape(SH.roundRect,{x:1.2,y:5.85,w:10.9,h:.48,rectRadius:.08,fill:{color:'EAFBF6'},line:{color:'A7F3D0'}});text(s,'Separation of concerns: UI is independent of model vendor; providers are independent of generation phases; persistence is independent of export and integration.',1.43,5.99,10.45,.17,{fontSize:10.5,color:C.teal,align:'center',margin:0});}

// 5
{const s=slide('AI generation pipeline','Four bounded phases improve completeness, traceability, and recovery from partial failures.');const phases=[['Phase 1','Epic generation','Extract feature areas and produce 10+ epics','1 model call'],['Phase 2','Story generation','Generate 5+ specific stories for each epic','1 call / epic'],['Phase 3','Task generation','Generate 4+ measurable developer tasks per story','1 call / epic'],['Phase 4','QA case generation','Create 2–3 manual QA cases per task in batches','1 call / task batch']];phases.forEach((p,i)=>{const x=.55+i*3.18;s.addShape(SH.roundRect,{x,y:1.65,w:2.78,h:3.72,rectRadius:.1,fill:{color:i%2?'F8FAFC':'EEF2FF'},line:{color:i%2?C.line:'C7D2FE'}});pill(s,p[0],x+.23,1.92,1.05,i===3?'DCFCE7':'E0E7FF',i===3?C.green:'3730A3');text(s,p[1],x+.23,2.45,2.3,.4,{fontSize:15,bold:true,color:C.navy});text(s,p[2],x+.23,3.12,2.3,.72,{fontSize:10.5,color:C.muted,valign:'top'});s.addShape(SH.roundRect,{x:x+.23,y:4.58,w:2.28,h:.42,rectRadius:.07,fill:{color:C.white},line:{color:C.line}});text(s,p[3],x+.23,4.69,2.28,.14,{fontSize:9,bold:true,color:C.indigo,align:'center',margin:0});if(i<3)arrow(s,x+2.79,3.47,x+3.12,3.47,C.indigo)});text(s,'Why this matters: smaller, typed requests are easier to validate and retry than one very large, fragile “generate everything” response.',.85,5.93,11.5,.3,{fontSize:13,color:C.teal,align:'center'});}

// 6
{const s=slide('Prompt engineering: structure over free-form generation','Every stage has a focused system prompt and an exact JSON contract.');box(s,.62,1.35,3.85,4.65,'System prompt controls','• Assigns a senior PM / developer / QA role\n• Defines deliverables for that phase only\n• Requires edge cases and error states\n• Sets minimum output depth\n• Prohibits commentary and Markdown fences',C.indigo);box(s,4.74,1.35,3.85,4.65,'User message controls','• Sends only relevant project context\n• Story/task parent IDs are explicitly listed\n• Requests exact counts per phase\n• Limits prompt size through contextualization\n• Includes prior clarification answers',C.blue);box(s,8.86,1.35,3.85,4.65,'Example contract','Task output must include:\n\n• valid story_id\n• one-action title\n• implementation description\n• measurable definition of done\n• estimate, dependencies, priority',C.teal);s.addText('Prompt principle: specificity is supplied by the system, scope is supplied by the brief, and linkage is supplied by known IDs.',{x:1.05,y:6.3,w:11.1,h:.32,fontSize:14,bold:true,color:C.navy,align:'center',margin:0});}

// 7
{const s=slide('Guardrails and quality controls','The application treats model output as untrusted until it passes structural and quality checks.');const data=[['Input guardrails','Brief validator checks length, users, features, and objective. Long inputs are contextualized and capped.','Input quality'],['Clarification loop','When a brief is vague, the app asks focused questions. It caps the loop at three rounds.','Ambiguity'],['Schema validation','Pydantic constrains priorities, statuses, confidence values, sizes, test types, and metric ranges.','Malformed data'],['Link validation','Tasks referencing unknown stories and tests referencing unknown tasks are rejected.','Broken hierarchy'],['Quality score','Coverage, story quality, task quality, gaps, and input quality create trusted/review/low status.','Overconfidence'],['Export gate','Export is blocked when backlog depth is below minimum epic/story/task thresholds.','Shallow plans']];data.forEach((d,i)=>{const col=i%2,row=Math.floor(i/2),x=.65+col*6.15,y=1.35+row*1.67;box(s,x,y,5.72,1.32,d[0],d[1],i===5?C.red:i===4?C.amber:C.indigo);pill(s,d[2],x+4.22,y+.88,1.18,'F8FAFC',C.muted)});}

// 8
{const s=slide('LiteLLM provider strategy','One model interface supports multi-provider reliability without coupling business logic to a single vendor.');s.addShape(SH.roundRect,{x:.62,y:1.65,w:2.45,h:3.5,rectRadius:.1,fill:{color:'EEF2FF'},line:{color:'C7D2FE'}});text(s,'Generation pipeline',.85,2.05,2,.25,{fontSize:15,bold:true,color:C.navy,align:'center'});text(s,'provider.generate(\nsystem_prompt,\nuser_message\n)',.88,2.65,1.92,.9,{fontSize:13,color:C.indigo,align:'center'});arrow(s,3.15,3.37,4.0,3.37,C.indigo);s.addShape(SH.roundRect,{x:4.05,y:1.65,w:2.55,h:3.5,rectRadius:.1,fill:{color:C.white},line:{color:C.line}});text(s,'LiteLLM adapter',4.35,2.05,1.95,.25,{fontSize:15,bold:true,color:C.navy,align:'center'});text(s,'• temperature 0.3\n• 8K token cap\n• 3 retries\n• 120 sec timeout\n• usage + cost log',4.43,2.62,1.8,1.5,{fontSize:12,color:C.muted,valign:'top'});['Groq','Cerebras','Gemini'].forEach((p,i)=>{const y=1.73+i*1.18;s.addShape(SH.roundRect,{x:8.25,y,w:3.65,h:.7,rectRadius:.09,fill:{color:i===0?'ECFDF5':'FFFFFF'},line:{color:i===0?'A7F3D0':C.line}});text(s,p,8.55,y+.19,1.1,.18,{fontSize:13,bold:true,color:C.navy,margin:0});text(s,i===0?'active / selectable':'fallback if configured',9.68,y+.21,1.8,.16,{fontSize:10,color:C.muted,align:'right',margin:0});arrow(s,6.65,3.37,8.12,y+.35,i===0?C.green:C.indigo)});text(s,'Operational controls: request-rate tracking, daily quota tracking, live provider probes, fallback order, and a short circuit breaker when all providers are exhausted.',.8,5.86,11.8,.38,{fontSize:13,color:C.teal,align:'center'});}

// 9
{const s=slide('Data model and traceability','The generated backlog is persisted as a hierarchy, not merely as a block of model text.');const nodes=[['Epic','E1\nFeature area + priority',.85,1.75,2.42,C.indigo],['Story','S1\nPersona + AC + size',3.73,2.65,2.42,C.blue],['Task','T1\nDoD + estimate + dependency',6.61,3.55,2.42,C.teal],['Test Case','TC1\nSteps + expected result',9.49,4.45,2.42,C.green]];nodes.forEach((n,i)=>{s.addShape(SH.roundRect,{x:n[2],y:n[3],w:n[4],h:1.05,rectRadius:.1,fill:{color:C.white},line:{color:n[5],width:1.6}});text(s,n[0],n[2]+.16,n[3]+.15,2.1,.22,{fontSize:14,bold:true,color:n[5],align:'center'});text(s,n[1],n[2]+.15,n[3]+.52,2.12,.28,{fontSize:10.5,color:C.muted,align:'center'});if(i<nodes.length-1)arrow(s,n[2]+2.43,n[3]+.55,nodes[i+1][2]-.08,nodes[i+1][3]+.53,n[5])});box(s,.85,5.8,3.45,.67,'SQLite','Generation history + settings + normalized hierarchy',C.amber);box(s,4.95,5.8,3.45,.67,'Excel export','Shareable planning artifact with depth validation',C.green);box(s,9.05,5.8,3.45,.67,'Redmine push','Hierarchy maps to issue trackers after review',C.red);}

// 10
{const s=slide('Real-time user experience and failure handling','The UI does not hide model latency or failure; it communicates state as generation proceeds.');const stages=[['Connecting','Provider selected; request begins',C.blue],['Generating','SSE streams epics, stories, tasks, and tests',C.indigo],['Parsing','JSON is cleaned and mapped into typed objects',C.teal],['Scoring','Metrics and trust validation are calculated',C.amber],['Done / Action','Save, edit, export, or push to Redmine',C.green]];stages.forEach((st,i)=>{const x=.55+i*2.54;s.addShape(SH.roundRect,{x,y:2.05,w:2.12,h:1.35,rectRadius:.1,fill:{color:C.white},line:{color:st[2],width:1.2}});s.addShape(SH.ellipse,{x:x+.83,y:1.72,w:.47,h:.47,fill:{color:st[2]},line:{color:st[2]}});text(s,st[0],x+.18,2.3,1.75,.2,{fontSize:12.5,bold:true,color:C.navy,align:'center'});text(s,st[1],x+.16,2.67,1.8,.38,{fontSize:9.5,color:C.muted,align:'center',valign:'top'});if(i<4)arrow(s,x+2.14,2.72,x+2.48,2.72,C.muted)});box(s,.9,4.5,3.62,1.25,'Provider problem','Retry up to three times; fall back to another configured provider; show a clear rate-limit/exhaustion message.',C.red);box(s,4.85,4.5,3.62,1.25,'Bad model output','Remove fences, parse JSON, skip invalid records, retry phase-specific empty outputs, log diagnostic context.',C.amber);box(s,8.8,4.5,3.62,1.25,'Partial backlog','Continue independent epic work where possible and expose warnings rather than crashing the entire session.',C.teal);}

// 11
{const s=slide('What I built: engineering highlights','The value is in the system design around the LLM, not just the API call.');const highlights=[['Provider-agnostic AI layer','LiteLLM centralizes retries, fallbacks, costs, quotas, and provider switching.'],['Deterministic hierarchy','Dedicated phases and ID validation preserve Epic → Story → Task → Test Case relationships.'],['Human-in-the-loop workflow','Editable output, gap visibility, trust level, export gate, and confirmation before external actions.'],['Operational UX','SSE progress, live provider status, token/cost estimates, history, and readable errors.'],['Integration-ready delivery','Excel export plus Redmine project/issue integration provide a route into team workflows.'],['Testable Python design','Separate services, schemas, provider abstraction, rule-based path, and pytest coverage.']];highlights.forEach((h,i)=>{const col=i%2,row=Math.floor(i/2),x=.65+col*6.1,y=1.35+row*1.65;box(s,x,y,5.65,1.25,h[0],h[1],[C.indigo,C.blue,C.teal,C.green,C.amber,C.red][i]);});}

// 12
{const s=slide('Demo script for the presentation','A 5-minute walkthrough that makes the architecture tangible.');const steps=[['1 min','Show the brief input','Use a realistic project brief; point out pre-flight validation and token estimate.'],['1 min','Start generation','Show live SSE progress while epics, stories, and tasks appear.'],['1 min','Inspect quality controls','Open gaps/metrics; explain trusted vs review vs low status and editable artifacts.'],['1 min','Show provider settings','Show active provider, live status, model selection, quota awareness, and fallback design.'],['1 min','Close the loop','Edit an item, export Excel, then show scoped Redmine push capability.']];steps.forEach((st,i)=>{const y=1.35+i*1.02;s.addShape(SH.roundRect,{x:.8,y,w:1.2,h:.55,rectRadius:.08,fill:{color:i===4?'DCFCE7':'E0E7FF'},line:{color:i===4?'A7F3D0':'C7D2FE'}});text(s,st[0],.8,y+.18,1.2,.15,{fontSize:10,bold:true,color:i===4?C.green:'3730A3',align:'center',margin:0});text(s,st[1],2.35,y+.08,2.65,.2,{fontSize:14,bold:true,color:C.navy,margin:0});text(s,st[2],5.05,y+.06,6.95,.34,{fontSize:10.5,color:C.muted,margin:0});if(i<4)s.addShape(SH.line,{x:1.4,y:y+.58,w:0,h:.44,line:{color:'C7D2FE',width:1.2,dash:'dash'}})});}

// 13
{const s=slide('Production roadmap','The current implementation is a strong MVP; these are the next technical investments.');const rows=[['Security & governance','Authentication/RBAC, encrypted credentials, secret manager, audit logs, HTTPS, prompt-injection defenses'],['Scale & resilience','PostgreSQL, background job queue, resumable generations, backup/restore, multi-tenant boundaries'],['AI evaluation','Prompt/model versioning, golden test set, hallucination and traceability metrics, feedback loop'],['Observability','Request IDs, central logs, error monitoring, latency/cost dashboards, provider outage alerts'],['Delivery maturity','CI/CD, tests in pipeline, container deployment, staging, feature flags, rollback plan']];rows.forEach((r,i)=>{const y=1.35+i*1.02;s.addShape(SH.roundRect,{x:.62,y,w:2.48,h:.63,rectRadius:.07,fill:{color:['EEF2FF','E0F2FE','ECFDF5','FFF7ED','FEF2F2'][i]},line:{color:C.line}});text(s,r[0],.82,y+.19,2.08,.17,{fontSize:11,bold:true,color:C.navy,align:'center',margin:0});text(s,r[1],3.38,y+.11,8.85,.32,{fontSize:11.2,color:C.muted,margin:0});});}

// 14
{const s=pptx.addSlide();s.background={color:C.navy};s.addShape(SH.rect,{x:0,y:0,w:13.333,h:.14,fill:{color:'818CF8'},line:{color:'818CF8'}});s.addText('Thank you',{x:.72,y:1.05,w:4.5,h:.55,fontSize:34,bold:true,color:C.white,margin:0});s.addText('AutoSDLC turns project understanding into an actionable, validated delivery plan.',{x:.75,y:1.93,w:7.25,h:.48,fontSize:17,color:'CBD5E1',margin:0});s.addShape(SH.roundRect,{x:.75,y:3.05,w:11.75,h:1.48,rectRadius:.12,fill:{color:'1E3A5F'},line:{color:'315A82'}});s.addText('“The LLM is one component. The product value comes from the workflow, guardrails, traceability, and integrations built around it.”',{x:1.18,y:3.5,w:10.9,h:.45,fontSize:20,bold:true,color:C.white,align:'center',margin:0});pill(s,'Questions & live demo',.75,5.5,2.0,'312E81','E0E7FF');s.addText('React • FastAPI • LiteLLM • SQLite • Redmine • SSE',{x:.75,y:6.48,w:5,h:.22,fontSize:10,color:'94A3B8',margin:0});}

pptx.writeFile({ fileName: 'AutoSDLC_Story_Generator_Technical_Presentation.pptx' });
